/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package archive.voting.application;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author i_lke
 */

public class NonBinaryBallotDialog extends javax.swing.JDialog {

    /**
     * Creates new form NonBinaryBallotDialog
     */
    public NonBinaryBallotDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Demonstration only
        lblBallotName.setText("Best Prototype");
        //rbCandidate1.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCandidates = new javax.swing.ButtonGroup();
        lblBallotName = new javax.swing.JLabel();
        SchoolLogo = new javax.swing.JRadioButton();
        CompanyLogo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        pCandidates = new javax.swing.JPanel();
        rbCandidate1 = new javax.swing.JRadioButton();
        rbCandidate2 = new javax.swing.JRadioButton();
        rbCandidate3 = new javax.swing.JRadioButton();
        rbCandidate4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBallotName.setText("Best Prototype:");

        SchoolLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/voting/application/Logo_S.png"))); // NOI18N
        SchoolLogo.setIconTextGap(2);

        CompanyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/voting/application/Logo_C.png"))); // NOI18N
        CompanyLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLogoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel4.setText("Non-Binary Ballot Screen");

        bgCandidates.add(rbCandidate1);
        rbCandidate1.setText("Candidate1");

        bgCandidates.add(rbCandidate2);
        rbCandidate2.setText("Candidate2");

        bgCandidates.add(rbCandidate3);
        rbCandidate3.setText("Candidate3");

        bgCandidates.add(rbCandidate4);
        rbCandidate4.setText("Candidate4");
        rbCandidate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCandidate4ActionPerformed(evt);
            }
        });

        bgCandidates.add(jRadioButton1);
        jRadioButton1.setText("Candidate5");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        bgCandidates.add(jRadioButton2);
        jRadioButton2.setText("Candidate6");

        bgCandidates.add(jRadioButton3);
        jRadioButton3.setText("Candidate7");

        bgCandidates.add(jRadioButton4);
        jRadioButton4.setText("Candidate8");

        jRadioButton5.setText("Candidate9");

        jRadioButton6.setText("Candidate10");

        javax.swing.GroupLayout pCandidatesLayout = new javax.swing.GroupLayout(pCandidates);
        pCandidates.setLayout(pCandidatesLayout);
        pCandidatesLayout.setHorizontalGroup(
            pCandidatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCandidatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCandidatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCandidate1)
                    .addComponent(rbCandidate2)
                    .addComponent(rbCandidate4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(rbCandidate3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCandidatesLayout.setVerticalGroup(
            pCandidatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCandidatesLayout.createSequentialGroup()
                .addComponent(rbCandidate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCandidate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCandidate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCandidate4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton6))
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CompanyLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SchoolLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBallotName)
                                    .addComponent(pCandidates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SchoolLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CompanyLogo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBallotName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pCandidates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompanyLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyLogoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(chkCandidate() == true)
        {
            if(JOptionPane.showConfirmDialog(this, "Are you sure that you want to vote for " + this.getCandidate()) == 0)
            {
                JOptionPane.showMessageDialog(this, "Thank you for voting.");
                this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a choice.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rbCandidate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCandidate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCandidate4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed
public boolean chkCandidate()
    {
        Boolean check = false;
        Component [] type = pCandidates.getComponents();
        for(Component x: type)
        {
              JRadioButton tempBox = (JRadioButton) x;
              if(tempBox.isSelected())
              {
                  check = true;
              }
        }   
        return check;
    }
    
    public String getCandidate()
    {
        String strAnswer = new String();
        
        Component [] size = pCandidates.getComponents();
        for(Component x: size)
        {
            try
            {
              JRadioButton tempBox = (JRadioButton) x;
                if(tempBox.isSelected())
                {
                    strAnswer = tempBox.getText();
                }
            }
            catch(Exception ex){
                System.out.println("Cast Error");
            }
        }
        return strAnswer;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonBinaryBallotDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonBinaryBallotDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonBinaryBallotDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonBinaryBallotDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NonBinaryBallotDialog dialog = new NonBinaryBallotDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CompanyLogo;
    private javax.swing.JRadioButton SchoolLogo;
    private javax.swing.ButtonGroup bgCandidates;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JLabel lblBallotName;
    private javax.swing.JPanel pCandidates;
    private javax.swing.JRadioButton rbCandidate1;
    private javax.swing.JRadioButton rbCandidate2;
    private javax.swing.JRadioButton rbCandidate3;
    private javax.swing.JRadioButton rbCandidate4;
    // End of variables declaration//GEN-END:variables
}
